- docs/zh_cn/user_guides/yolov5_tutorial.md
Add Tensorboard usage method in yolov5_tutorial.md
> [Doc] Add Tensorboard usage method of yolov5_tutorial.md

- mmyolo/datasets/transforms/mix_img_transforms.py
> Use 'Compose' directly

- mmyolo/models/necks/base_yolo_neck.py
BaseYOLONeck中的forward的输入inputs类型注解错误，经测试为List[torch.Tensor]，为避免后续人员将其误认为只是单一的Tenosr类型，故做修改
修改了BaseYOLONeck类中forward方法中的inputs的类型注解
没
无
1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream …
> fix type hints

- tools/test.py
Implement dump results
Support dump predictions to a pickle file for offline evaluation in tools/test.py
> [Feature]Implement dump results 

- README.md
- README_zh-CN.md
- docs/en/overview.md
- docs/zh_cn/algorithm_descriptions/yolov5_description.md
- docs/zh_cn/overview.md
Update image in docs.
1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMDetection or MMClassification.
4. The documentation has been modified accordingly, like docstring or example tutorials.
> [Docs] Remove README image and update overview docs

- docs/zh_cn/algorithm_descriptions/rtmdet_description.md
- docs/zh_cn/algorithm_descriptions/yolov5_description.md
Add the model description of RTMDet.
rtmdet_description.md
> [Doc] Add the model description in rtmdet_description.md

- README_zh-CN.md
- docs/zh_cn/algorithm_descriptions/index.rst
- docs/zh_cn/algorithm_descriptions/rtmdet_description.md
- docs/zh_cn/algorithm_descriptions/yolov5_description.md
> Refine RTMDet docs

- docs/zh_cn/get_started.md
- docs/zh_cn/user_guides/yolov5_tutorial.md
Fix the get_started.md and yolov5_tutorial.md
> [Does]Fix the get_started.md and yolov5_tutorial.md

- configs/yolov6/yolov6_s_syncbn_8xb32-400e_coco.py
- configs/yolov6/yolov6_s_syncbn_fast_8xb32-400e_coco.py
- mmyolo/models/dense_heads/yolov6_head.py
- mmyolo/models/losses/iou_loss.py
- mmyolo/models/task_modules/__init__.py
- mmyolo/models/task_modules/assigners/__init__.py
- mmyolo/models/task_modules/assigners/batch_atss_assigner.py
- mmyolo/models/task_modules/assigners/batch_task_aligned_assigner.py
> support Yolov6 train

- configs/yolov6/yolov6_s_syncbn_8xb32-400e_coco.py
Add YOLOv6 lr scheduler
`configs/yolov6/yolov6_s_syncbn_8xb32-400e_coco.py`
> [Feature] Add YOLOv6 lr scheduler

- configs/yolov6/yolov6_s_syncbn_8xb32-400e_coco.py
Add YOLOv6 stop aug hook
yolov6 config file
> [Feature] Add YOLOv6 stop aug hook

- configs/yolov6/yolov6_s_syncbn_8xb32-400e_coco.py
Add YOLOv6 save best ckpt config
yolov6 config
> [Feature] Add YOLOv6 save best ckpt config

- configs/yolov6/yolov6_s_syncbn_8xb32-400e_coco.py
> [Feature] Improve YOLOv6 PipelineSwitchHook

- configs/yolov6/yolov6_s_syncbn_8xb32-400e_coco.py
Fix YOLOv6 train pipeline stage 2
config yolov6 s
> [Fix] Fix YOLOv6 train pipeline stage 2

- configs/yolov6/yolov6_s_syncbn_8xb32-400e_coco.py
Fix YOLOv6 train pipeline
yolov6 config file
> [Fix] Fix YOLOv6 train pipeline

- .circleci/test.yml
- README.md
- README_zh-CN.md
- docs/en/get_started.md
- docs/en/user_guides/yolov5_tutorial.md
- docs/zh_cn/get_started.md
- docs/zh_cn/user_guides/yolov5_tutorial.md
- mmyolo/__init__.py
- requirements/mminstall.txt
- setup.py
> Fix CI due to mmengine update to 0.2.0

- docker/Dockerfile
- docs/en/get_started.md
- docs/zh_cn/get_started.md
Install mmengine==0.1.0 for now
> [Docs] Limit mmengine version

- mmyolo/datasets/transforms/transforms.py
- tests/test_datasets/test_transforms/test_transforms.py
Based on https://github.com/open-mmlab/mmdetection/pull/8784.
1. Pre-commit or other linting tools are used to …
> [Feature] Support LoadAnnotations when excluding instances

- configs/rtmdet/rtmdet_l_syncbn_8xb32-300e_coco.py
- configs/yolov5/yolov5_s-v61_syncbn_8xb16-300e_coco.py
Fix `RTMDet` visualization bug in test_pipeline config
1. Pre-commit or other …
> [Fix] RTMDet visualization bug in test_pipeline config

- configs/yolov7/yolov7_l_fast_8x16b-300_coco.py
- configs/yolov7/yolov7_l_syncbn_fast_8x16b-300_coco.py
- mmyolo/models/backbones/__init__.py
- mmyolo/models/backbones/yolov7_backbone.py
- mmyolo/models/dense_heads/__init__.py
- mmyolo/models/dense_heads/yolov7_head.py
- mmyolo/models/layers/__init__.py
- mmyolo/models/layers/yolo_bricks.py
- mmyolo/models/necks/__init__.py
- mmyolo/models/necks/base_yolo_neck.py
- mmyolo/models/necks/yolov7_pafpn.py
- tools/model_converters/yolov7_to_mmyolo.py
> [Feature] Support YOLOv7 inference

- configs/yolov6/yolov6_s_syncbn_8xb32-400e_coco.py
- configs/yolov6/yolov6_s_syncbn_fast_8xb32-300e_coco.py
- configs/yolov6/yolov6_s_syncbn_fast_8xb32-400e_coco.py
- mmyolo/models/task_modules/assigners/batch_atss_assigner.py
- mmyolo/models/task_modules/assigners/batch_task_aligned_assigner.py
- tests/test_models/test_task_modules/__init__.py
- tests/test_models/test_task_modules/test_assigners/__init__.py
- tests/test_models/test_task_modules/test_assigners/test_batch_atss_assigner.py
Refactor YOLOv6 BatchATSSAssigner and add UT
`mmyolo/models/task_modules/assigners/batch_atss_assigner.py`
UT: `tests/test_models/test_task_modules/test_assigners/test_batch_atss_assigner.py`
> [Refactor] YOLOv6 BatchATSSAssigner

- configs/yolov6/yolov6_s_syncbn_fast_8xb32-400e_coco.py
- mmyolo/models/task_modules/assigners/batch_atss_assigner.py
- mmyolo/models/task_modules/assigners/batch_task_aligned_assigner.py
Fix YOLOv6 training iou calculate error
Add YOLOv6 iou calculator in `mmyolo/models/task_modules/assigners/batch_atss_assigner.py`
> [Fix] Fix YOLOv6 training iou calculate error

- docs/en/advanced_guides/how_to.md
- docs/zh_cn/advanced_guides/how_to.md
- docs/zh_cn/user_guides/config.md
- mmyolo/models/dense_heads/yolov5_head.py
- mmyolo/models/dense_heads/yolox_head.py
Document error modification，change `--cfg-options data.train.pipeline.0.type=LoadImageFromNDArray`to` --cfg-options data.train.pipeline.0.type=LoadImageFromWebcam`.
> [Docs] Fix some errors in `config.md` and `how_to.md`

- .circleci/test.yml
- README.md
- README_zh-CN.md
- docker/Dockerfile
- docs/en/get_started.md
- docs/en/user_guides/yolov5_tutorial.md
- docs/zh_cn/article.md
- docs/zh_cn/get_started.md
- docs/zh_cn/user_guides/yolov5_tutorial.md
- mmyolo/__init__.py
- mmyolo/version.py
- requirements/mminstall.txt
- requirements/readthedocs.txt
> update mmengine/mmdet version and article

- mmyolo/models/losses/iou_loss.py
Refactor func `bbox_overlaps`
`mmyolo/models/losses/iou_loss.py`
> [Refactor] func `bbox_overlaps`

- MANIFEST.in
> Fix bug in pypi not including .mim folder

- docs/en/_static/css/readthedocs.css
- docs/en/conf.py
- docs/zh_cn/_static/css/readthedocs.css
1. Adjust the logo size
2. Fix the language type of EN Readthedocs
1. readthedocs.css
2. conf.py
> [Docs] Optimize Readthedocs page display

- mmyolo/models/dense_heads/yolov6_head.py
- mmyolo/models/losses/iou_loss.py
> [Fix] Improve v6 coding

- mmyolo/models/losses/iou_loss.py
> [Fix] Improve bbox_overlaps

- mmyolo/models/dense_heads/yolov6_head.py
> [Fix] Add common attributes to reduce calculation for YOLOv6

- mmyolo/models/dense_heads/yolov6_head.py
> [Fix] Improve coding

- mmyolo/models/dense_heads/yolov6_head.py
> [Fix] fix YOLOv6 bug

- docker/Dockerfile_deployment
- docs/zh_cn/deploy/yolov5_deployment.md
[BUG] Fix opencv new version bug
> [BUG] Fix opencv new version bug

- README.md
- README_zh-CN.md
- docs/en/algorithm_descriptions/model_design.md
- docs/en/algorithm_descriptions/yolov5_description.md
- docs/zh_cn/algorithm_descriptions/model_design.md
- docs/zh_cn/algorithm_descriptions/rtmdet_description.md
- docs/zh_cn/algorithm_descriptions/yolov5_description.md
- mmyolo/models/necks/base_yolo_neck.py
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, make the pull request and seek help from maintainers.
According to the code, https://github.com/open-mmlab/mmyolo/blob/0b48313dc757a26ad3087aa17f0991833bd7cc91/mmyolo/models/necks/base_yolo_neck.py#L245-L251, the layer numbers should be
> [Fix] Wrong layer number in model graph

- tools/test.py
Motivation
Fix incorrect hard code of adding DumpResults in config.
Modification
Directly add the DumpResults objects to the runner's evaluator.
> [Fix]update dump results

- docs/en/algorithm_descriptions/yolov5_description.md
Fix typo in yolov5_description.md.
2. …
> Fix typo in yolov5_description.md

- mmyolo/models/backbones/cspnext.py
- setup.cfg
link https://github.com/open-mmlab/mmdetection/pull/9265
> [Update] Change the typing import method based on mmdet

- mmyolo/models/backbones/efficient_rep.py
- mmyolo/models/layers/yolo_bricks.py
Add docstring
`mmyolo/models/layers/yolo_bricks.py`
> [Improvement] Add docstr for YOLOv6

- mmyolo/models/backbones/csp_darknet.py
- mmyolo/models/backbones/efficient_rep.py
> Support `init_cfg` in backbone 

- docs/en/user_guides/useful_tools.md
- docs/zh_cn/user_guides/useful_tools.md
1.Add voc2012 instruction in download_dataset
2.Modify model_converters folder path
> [Docs] Fix useful_tools.md

- README.md
- README_zh-CN.md
- demo/featmap_vis_demo.py
- demo/image_demo.py
- docs/en/advanced_guides/index.rst
- docs/en/advanced_guides/plugins.md
- docs/en/notes/changelog.md
- docs/en/overview.md
- docs/zh_cn/advanced_guides/index.rst
- docs/zh_cn/advanced_guides/plugins.md
- docs/zh_cn/notes/changelog.md
- docs/zh_cn/overview.md
- mmyolo/models/plugins/cbam.py
- mmyolo/version.py
> Add v0.1.3 Change log 

- docs/en/advanced_guides/how_to.md
- docs/en/advanced_guides/plugins.md
- docs/zh_cn/advanced_guides/how_to.md
- docs/zh_cn/advanced_guides/plugins.md
Add two examples of backbone replacement and translate `plugin.md` in to EN
`how_to.md` and `plugin.md`
> [Docs] Add two examples of backbone replacement and update `plugin.md` in EN

- docs/en/user_guides/config.md
- docs/zh_cn/user_guides/config.md
To fix https://github.com/open-mmlab/mmyolo/issues/299.
`user_guides/config.md`
> [Docs] Fix invalid urls in `user_guides/config.md`

- mmyolo/datasets/transforms/mix_img_transforms.py
Add mosaic9 graph in docstring.
```python
+-------------------------------+------------+
| pad           |      pad      |            |
|    +----------+               |            |
|    |          +---------------+  top_right |
|    |          |      top      |   image2   |
|    | top_left |     image1    |            |
|    |  image8  o--------+------+--------+---+
|    |          |        |               |   |
+----+----------+        |     right     |pad|
|               | center |     image3    |   |
|     left      | image0 +---------------+---|
|    image7     |        |               |   |
+---+-----------+---+--------+               |   |
|   |  cropped  |            |  bottom_right |pad|
|   |bottom_left|            |    image4     |   |
|   |  image6   |   bottom   | …
```
> [Improvement] Add mosaic9 graph in docstring

- docs/en/user_guides/useful_tools.md
- docs/zh_cn/user_guides/useful_tools.md
- tools/analysis_tools/browse_coco_json.py
`data_root` of `tools/analysis_tools/browse_coco_json.py` is not necessary.
`tools/analysis_tools/browse_coco_json.py`
> [Improvement] Improve browse coco json script args

- tools/dataset_converters/labelme2coco.py
Add labelme2coco script
`tools/dataset_converters/labelme2coco.py`
> [Feature] Add `labelme2coco` script

- configs/deploy/detection_tensorrt-int8_dynamic-192x192-960x960.py
- configs/deploy/detection_tensorrt-int8_static-640x640.py
Int8 deployment failed with cannot find calib config.
Move calib config outside backend config.
None.
Used in mmdeploy tools/deploy.py int8 deployment.
4. The documentation has …
> [Fix] Fix mmyolo int8 deploy config

- docs/en/advanced_guides/how_to.md
- docs/zh_cn/advanced_guides/how_to.md
- tools/test.py
Add option of json output in `test.py`
`test.py` and `how_to.md`
> [Enhance] Add option of json output in `test.py`

- mmyolo/datasets/transforms/mix_img_transforms.py
https://github.com/open-mmlab/mmdetection/pull/9259#issuecomment-1306546492
the same as https://github.com/open-mmlab/mmdetection/pull/9259
> [Fix] MixUp padding

- docs/en/community/code_style.md
- docs/en/community/contributing.md
- docs/en/index.rst
- docs/zh_cn/community/code_style.md
- docs/zh_cn/community/contributing.md
- docs/zh_cn/index.rst
Add `contributing.md` and `code_style.md`
https://github.com/open-mmlab/mmcv/pull/1941
https://github.com/open-mmlab/mmcv/pull/2406
> [Docs] Add `contributing.md` and `code_style.md`

- docs/en/user_guides/useful_tools.md
- docs/zh_cn/advanced_guides/how_to.md
- docs/zh_cn/user_guides/useful_tools.md
Add docs about how to use mim to call scripts across libraries.
`how_to.md`
> [Docs] Add docs about how to use mim to run scripts across libraries

- docs/en/advanced_guides/how_to.md
- docs/zh_cn/advanced_guides/how_to.md
Update EN `how_to.md` with the examples of mim.
`how_to.md`
> [Docs] Update EN `how_to.md` with the examples of mim

- README.md
- README_zh-CN.md
- docs/en/get_started.md
- docs/en/notes/changelog.md
- docs/zh_cn/get_started.md
- docs/zh_cn/notes/changelog.md
- mmyolo/version.py
- model-index.yml
> add changelog of v0.2.0

- mmyolo/models/dense_heads/yolov5_head.py
fix twice head inference bug.
1. Pre-commit or other linting tools are used to fix …
> [Fix] Fix twice head inference bug

- docs/en/user_guides/useful_tools.md
- docs/zh_cn/user_guides/useful_tools.md
- tools/analysis_tools/browse_dataset.py
Improve args for `browse_dataset` and supprot `RepeatDataset`
- `docs/zh_cn/user_guides/useful_tools.md`
- `docs/en/user_guides/useful_tools.md`
- `tools/analysis_tools/browse_dataset.py`
> [Improvement] Improve args for `browse_dataset` and supprot `RepeatDataset`

- demo/large_image_demo.py
- tests/test_deploy/test_object_detection.py
> [Enhancement] Optimize the vis results of large images in `debug` mode

- demo/deploy_demo.py
Add deploy demo
`demo/deploy_demo.py`
> [Feature] Add deploy demo

- mmyolo/deploy/models/dense_heads/yolov5_head.py
- mmyolo/deploy/models/layers/bbox_nms.py
- mmyolo/deploy/object_detection.py
- mmyolo/models/task_modules/assigners/batch_yolov7_assigner.py
Add docstring to all remaining files
> [Improvement] Add docstring to all remaining files

- .circleci/test.yml
> Change torch version to 1.13 in CI

- mmyolo/deploy/models/dense_heads/yolov5_head.py
- tests/test_deploy/test_mmyolo_models.py
We have refactored function rewriter of MMDeploy to support MMRazor in the future, which leads to broken in mmyolo.
If this PR introduces a new feature, it is better to list some use cases here and update the …
> [Fix] Fix mmdeploy rewriter

- docs/zh_cn/advanced_guides/module_combination.md
> [CodeCamp] Add doc of `module_combination`

- configs/yolov5/README.md
- configs/yolov5/crowdhuman/yolov5_s-v61_fast_8xb16-300e_crowdhuman.py
- mmyolo/datasets/__init__.py
- mmyolo/datasets/yolov5_crowdhuman.py
> [Feature] Add `crowdhuman` dataset

- docs/zh_cn/algorithm_descriptions/yolov6_description.md
Add doc of yolov6_description.md
Add description of Label Assigment and Loss function
> [CodeCamp] Add doc of yolov6_description.md

- docs/en/advanced_guides/how_to.md
- docs/zh_cn/advanced_guides/how_to.md
Add docs about how to set the random seed.
`how_to.md`
> [Docs] Add docs about how to set the  random seed

- tools/dataset_converters/labelme2coco.py
Link issue #390 
Add raise when class is blank or space between words
> [Fix] Add raise when class is blank or space between words

- tools/train.py
> [Enhance]: Add resume from specific checkpoint in CLI

- configs/yolox/README.md
add yolox structure description
add the url of yolox structure picture in ./configs/yolox/README.md
4. The documentation has been modified accordingly, like docstring or example …
> CodeCamp #1519 [Docs] add yolox structure description

- projects/easydeploy/model/__init__.py
- projects/easydeploy/model/backendwrapper.py
- projects/easydeploy/tools/build_engine.py
- projects/easydeploy/tools/export.py
- projects/easydeploy/tools/image-demo.py
Support pytorch model forward for TensorRT inference.
Pytorch forward will be faster than normal python object `__call__` function.
> [Feature] Support PyTorch model forward for TensorRT inference

- .circleci/test.yml
- docs/zh_cn/user_guides/custom_dataset.md
- projects/assigner_visualization/visualization/assigner_visualizer.py
Set metainfo fields to lower case
> [Fix] Set metainfo fields to lower case and  fix CI

- docs/en/advanced_guides/how_to.md
- docs/zh_cn/advanced_guides/how_to.md
> [CodeCamp] Add docs about how to freeze the weight of backbone or neck

- README.md
- README_zh-CN.md
Update document links in README.md
README.md
README_zh-CN.md
4. The documentation has …
> [Docs] Update deployment doc urls in README

- configs/yolov5/yolov5_s-v61_syncbn_fast_1xb4-300e_balloon.py
Link issue https://github.com/open-mmlab/mmyolo/issues/420
> [Fix] Fix customize dataset training

- demo/image_demo.py
- projects/easydeploy/model/model.py
- projects/easydeploy/tools/export.py
- projects/easydeploy/tools/image-demo.py
Support YOLOv7 easy deploy:
1. Export ONNX and build TensorRT engine.
2. Image demo for image or video
3. Fix mkdir for creating dir recursively
> [Deploy] Support YOLOv7 easy deploy

- configs/rtmdet/rtmdet_s_syncbn_fast_8xb32-300e_coco.py
- mmyolo/models/necks/cspnext_pafpn.py
Fix neck when out stages larger than 3.
Fix RTMDet-s stage2 training config.
1. Pre-commit or other linting tools …
> [Fix] Fix rtmdet neck and config.

- docs/zh_cn/algorithm_descriptions/yolov6_description.md
Add the Network Structure section doc of yolov6_description.md …
> [CodeCamp]Add doc of  yolov6_description.md

- mmyolo/models/dense_heads/rtmdet_head.py
- projects/assigner_visualization/assigner_visualization.py
Distinguish variables when training and testing to avoid error while using multi-scale training.
> Fix potential bugs in rtmdet multi-scale training

- configs/rtmdet/README.md
- configs/yolov5/README.md
- configs/yolov6/README.md
- configs/yolox/README.md
- docs/en/algorithm_descriptions/yolov5_description.md
- docs/zh_cn/algorithm_descriptions/yolov5_description.md
Update model graphs.
1. Fix some errors in YOLOX and YOLOv5-P6 model graphs.
2. Add model graphs in config README.
> [Docs] Update model graphs

- .circleci/test.yml
- docs/en/get_started.md
- docs/zh_cn/get_started.md
- setup.py
Adjust the minimum supported python version to 3.7
If this PR introduces a new feature, it is better to list some use cases here …
> [Fix] adjust the minimum supported python version to 3.7

- projects/easydeploy/bbox_code/__init__.py
- projects/easydeploy/bbox_code/bbox_coder.py
- projects/easydeploy/model/model.py
- projects/easydeploy/nms/trt_nms.py
Add new YOLOX bbox coder for TensorRT-8 and fix TensorRT-7 bug
> [Feature] Add new YOLOX bbox coder for TensorRT-8 and fix TensorRT-7 bug

- configs/yolov8/README.md
Add the model structure graph of YOLOv8-P5
> [Doc] Add the model structure graph of YOLOv8-P5

- projects/easydeploy/backbone/__init__.py
- projects/easydeploy/backbone/common.py
- projects/easydeploy/model/model.py
- projects/easydeploy/tools/export.py
- projects/easydeploy/tools/image-demo.py
[Deploy] Support YOLOv8 deploy
> [Deploy] Support YOLOv8 deploy

- configs/yolov8/README.md
- projects/easydeploy/backbone/common.py
Add missing background frame in YOLOv8 graph
> [Fix] Fix YOLOv8 graph and a lint issue

- projects/easydeploy/model/backendwrapper.py
> [Fix] Fix requirement about only ONNXRuntime without TensorRT

- docs/en/get_started.md
- docs/zh_cn/get_started.md
> [Doc] Fix the installation step 1 on Colab

- configs/ppyoloe/README.md
Add PPYOLOE model structure
If this PR introduces a new feature, it is better to list some use cases here and update the …
> [Doc] Add PPYOLOE model structure

- mmyolo/models/necks/cspnext_pafpn.py
> Support RTMDet P6 config

- .gitignore
- docs/en/user_guides/useful_tools.md
- docs/zh_cn/user_guides/useful_tools.md
- tools/analysis_tools/vis_scheduler.py
Add a tool for scheduler visualization
1. `tools/analysis_tools/vis_scheduler.py`
2. related docs
3. gitignore
> [Feature] Add a tool for scheduler visualization

- docs/en/model_zoo.md
- docs/zh_cn/article.md
- docs/zh_cn/model_zoo.md
Update `article.md` and `model_zoo.md`
> [Docs] Update `article.md` and `model_zoo.md`

- .pre-commit-config-zh-cn.yaml
- .pre-commit-config.yaml
Link https://github.com/open-mmlab/mmeval/pull/86
> dev: Use official isort

- configs/yolov5/yolov5_m-p6-v62_syncbn_fast_8xb16-300e_coco.py
- configs/yolov5/yolov5_m-v61_syncbn_fast_8xb16-300e_coco.py
- configs/yolov5/yolov5_s-p6-v62_syncbn_fast_8xb16-300e_coco.py
- configs/yolov5/yolov5_s-v61_syncbn-detect_8xb16-300e_coco.py
- configs/yolov5/yolov5_s-v61_syncbn_8xb16-300e_coco.py
- configs/yolov5/yolov5_s-v61_syncbn_fast_1xb4-300e_balloon.py
> Beautify the YOLOv5 configuration

- configs/yolov7/README.md
Understand model structure of YOLOv7 clearly and quickly.
add model structure graph of YOLOv7 in configs\yolov7\README.md.
1. Pre-commit or other linting tools are used to fix …
> [Docs] Add model structure graph of YOLOv7 in `configs\yolov7\README.md`

- docs/en/community/contributing.md
- docs/zh_cn/community/contributing.md
Added the prompt to submit the pull request part and modified the relevant picture, added a missing command, and modified two missing symbols.
> [Docs] Refine community/contributing.md

- projects/assigner_visualization/README.md
- projects/assigner_visualization/visualization/assigner_visualizer.py
> [Fix] fix typo for assigner visualization

- mmyolo/datasets/utils.py
- mmyolo/models/data_preprocessors/data_preprocessor.py
- tests/test_datasets/test_utils.py
- tests/test_models/test_data_preprocessor/test_data_preprocessor.py
Facilitates subsequent multitasking development
1. Pre-commit or other linting tools are used to fix potential …
> [Enchance] Extending `DetDataPreprocessor` flexibility

- configs/yolov5/yolov5_s-v61_syncbn_8xb16-300e_coco.py
- configs/yolov8/yolov8_l_syncbn_fast_8xb16-500e_coco.py
- configs/yolov8/yolov8_m_syncbn_fast_8xb16-500e_coco.py
- configs/yolov8/yolov8_s_syncbn_fast_8xb16-500e_coco.py
- mmyolo/datasets/transforms/transforms.py
Beautify the YOLOv8 configuration.
> Beautify the YOLOv8 configuration

- projects/easydeploy/bbox_code/bbox_coder.py
> Fix rtmdet decoder in easydeploy

- mmyolo/utils/__init__.py
- mmyolo/utils/misc.py
- tools/test.py
- tools/train.py
> [Enchance] judge `metainfo` is lower

- configs/rtmdet/rtmdet_l_syncbn_fast_8xb32-300e_coco.py
- configs/rtmdet/rtmdet_m_syncbn_fast_8xb32-300e_coco.py
- configs/rtmdet/rtmdet_s_syncbn_fast_8xb32-300e_coco.py
- configs/rtmdet/rtmdet_tiny_syncbn_fast_8xb32-300e_coco.py
- configs/rtmdet/rtmdet_x_syncbn_fast_8xb32-300e_coco.py
- configs/yolov5/yolov5_s-v61_syncbn_8xb16-300e_coco.py
> [Improve] Beauty RTMDet config

- configs/yolov6/yolov6_l_syncbn_fast_8xb32-300e_coco.py
- configs/yolov6/yolov6_m_syncbn_fast_8xb32-300e_coco.py
- configs/yolov6/yolov6_n_syncbn_fast_8xb32-300e_coco.py
- configs/yolov6/yolov6_n_syncbn_fast_8xb32-400e_coco.py
- configs/yolov6/yolov6_s_syncbn_fast_8xb32-300e_coco.py
- configs/yolov6/yolov6_s_syncbn_fast_8xb32-400e_coco.py
- configs/yolov6/yolov6_t_syncbn_fast_8xb32-300e_coco.py
- configs/yolov6/yolov6_t_syncbn_fast_8xb32-400e_coco.py
Beauty YOLOv6 config
YOLOv6 configs
> [Improve] Beautify YOLOv6 all configs

- configs/razor/subnets/rtmdet_tiny_ofa_lat31_syncbn_16xb16-300e_coco.py
Fix CI due to the new version of RTMDet config.
> [Fix] Fix CI due to the new version of RTMDet config

- projects/assigner_visualization/assigner_visualization.py
- projects/assigner_visualization/dense_heads/rtmdet_head_assigner.py
- projects/assigner_visualization/visualization/assigner_visualizer.py
> Fix RTMDet visualization to new code 

- configs/yolox/README.md
modify yolox_loss part
If this PR introduces a new feature, it is better to list some use cases here and update the …
> Update YOLOX README.md

- projects/assigner_visualization/assigner_visualization.py
- projects/assigner_visualization/configs/yolov8_s_syncbn_fast_8xb16-500e_coco_assignervisualization.py
- projects/assigner_visualization/dense_heads/__init__.py
- projects/assigner_visualization/dense_heads/rtmdet_head_assigner.py
- projects/assigner_visualization/dense_heads/yolov8_head_assigner.py
- projects/assigner_visualization/detectors/yolo_detector_assigner.py
- projects/assigner_visualization/visualization/assigner_visualizer.py
> YOLOv8 Assigner visualization 

- README.md
- README_zh-CN.md
> [Docs] Add twitter discord medium youtube link

- tools/model_converters/yolov7_to_mmyolo.py
> add yolov7-e6e weight converter

- projects/assigner_visualization/README.md
> add yolov8 visualization readme

- docs/zh_cn/recommended_topics/troubleshooting_steps.md
- docs/zh_cn/tutorials/faq.md
> [Docs] Refine doc about faq and troubleshooting_steps

- docs/zh_cn/get_started/15_minutes_object_detection.md
- docs/zh_cn/recommended_topics/troubleshooting_steps.md
- docs/zh_cn/tutorials/faq.md
> [Docs] Refine doc about troubleshooting_steps and 15_minutes_object_detection

- mmyolo/models/data_preprocessors/data_preprocessor.py
Link https://github.com/open-mmlab/mmdetection/pull/9723/files
> [Improve] Remove `cast_data`

- docs/zh_cn/common_usage/tta.md
> [Docs] Refine  TTA   Docs

- configs/yolov5/yolov5_s-v61_fast_1xb12-40e_608x352_cat.py
- demo/boxam_vis_demo.py
- docs/zh_cn/tutorials/faq.md
- mmyolo/utils/boxam_utils.py
> Fix box cam error

- docs/en/recommended_topics/contributing.md
- docs/zh_cn/recommended_topics/contributing.md
Added git and github configurations in contributing.md
> [Docs] Modify contributing.md

- README.md
- README_zh-CN.md
- docs/en/index.rst
- docs/en/recommended_topics/complexity_analysis.md
- docs/zh_cn/index.rst
- docs/zh_cn/recommended_topics/complexity_analysis.md
- mmyolo/models/dense_heads/yolov8_head.py
- tools/analysis_tools/get_flops.py
> [Feature] Support Calculate FLOPs

- docs/en/model_zoo.md
- docs/zh_cn/model_zoo.md
add plot image for model-zoo.
add image to model_zoo.md
2. The modification is covered by complete …
> add plot image for model-zoo

- configs/rtmdet/rotated/rtmdet-r_l_syncbn_fast_2xb4-36e_dota.py
- mmyolo/models/dense_heads/__init__.py
- mmyolo/models/dense_heads/rtmdet_head.py
- mmyolo/models/dense_heads/rtmdet_rotated_head.py
- tests/test_models/test_dense_heads/test_rotated_rtmdet_head.py
> [Fix] Change the name of RTMDet-R

- README.md
- README_zh-CN.md
> Update banner of v0.5.0 

- configs/yolov8/ins_seg/yolov8_ins_s_syncbn_fast_8xb16-500e_coco.py
- configs/yolov8/yolov8_ins_s_syncbn_fast_8xb16-500e_coco.py
- mmyolo/datasets/transforms/transforms.py
- mmyolo/models/dense_heads/__init__.py
- mmyolo/models/dense_heads/yolov8_ins_head.py
- tests/test_datasets/test_transforms/test_transforms.py
- tests/test_models/test_dense_heads/test_yolov8_head.py
- tools/model_converters/yolov8_to_mmyolo.py
Support YOLOv8 Ins Segmentation Inference
Can reproduce bbox and mask mAP on yolov8-s model.
Official mAP results:
> [Feature] Support YOLOv8 Ins Segmentation Inference

- demo/boxam_vis_demo.py
Adjust the order of package imports in `boxam_vis_demo.py` to make the `try/except` take effect.
> [Fix] Adjust the order of package imports in `boxam_vis_demo.py`

- mmyolo/models/dense_heads/yolov7_head.py
> [Bug] use `num_base_priors` to init bias instead of `3`

- docs/en/get_started/installation.md
fix installaion en doc error
fix installaion en doc error
If this PR introduces a new feature, it is better to list some use …
> [Fix] Fix installation en doc error

- mmyolo/datasets/transforms/transforms.py
> fix pad_param type

- docs/en/tutorials/faq.md
- docs/zh_cn/tutorials/faq.md
Translate faq.md.
docs/en/tutorials/faq.md
docs/zh/tutorials/faq.md
4. The …
> faq translate init

- README_zh-CN.md
- docs/zh_cn/get_started/15_minutes_object_detection.md
Some errors were found in the documentation when trying mmyolo.
docs/zh_cn/get_started/15_minutes_object_detection.md
README_zh-CN.md
> Fixed some errors in the documentation.

- mmyolo/models/dense_heads/ppyoloe_head.py
- projects/easydeploy/docs/model_convert.md
- projects/easydeploy/model/__init__.py
- projects/easydeploy/model/backend.py
- projects/easydeploy/model/model.py
- projects/easydeploy/tools/export_onnx.py
[Enhance] New easydeploy for extending new features.
> [Enhance] New easydeploy for extending new features.

- README.md
- README_zh-CN.md
> Update readme of playground project

- requirements/docs.txt
Fix doc CI error referring to https://github.com/open-mmlab/mmdetection/pull/10279
> [Fix] doc CI error

- docs/en/get_started/installation.md
fixes typo in installation command
> Fix typo in installation.md

- demo/15_minutes_object_detection.ipynb
- docs/en/get_started/15_minutes_object_detection.md
- docs/zh_cn/get_started/15_minutes_object_detection.md
Add `15_minutes_object_detection.ipynb`
> [Docs] Add `15_minutes_object_detection.ipynb`

- mmyolo/datasets/pose_coco.py
- mmyolo/models/losses/oks_loss.py
> fix lazy import of mmpose

- mmyolo/utils/boxam_utils.py
> fix gardcam error using in mmdet

- docs/en/recommended_topics/deploy/mmdeploy_guide.md
- docs/en/recommended_topics/deploy/mmdeploy_yolov5.md
- docs/zh_cn/recommended_topics/deploy/mmdeploy_guide.md
- docs/zh_cn/recommended_topics/deploy/mmdeploy_yolov5.md
> update deploy docs

- mmyolo/datasets/transforms/transforms.py
Fix `PPYOLOERandomCrop` and `MaskRefine`
> [Fix] Fix ppyoloerandomcrop

- README.md
- README_zh-CN.md
- docker/Dockerfile
- docker/Dockerfile_deployment
- docs/en/get_started/installation.md
- docs/en/notes/changelog.md
- docs/en/tutorials/custom_installation.md
- docs/zh_cn/get_started/installation.md
- docs/zh_cn/notes/changelog.md
- docs/zh_cn/tutorials/custom_installation.md
- mmyolo/__init__.py
> Add change log

- configs/yolov6/yolov6-face/yolov6_v3_l_syncbn_fast_8xb32-300e_widerface.py
- configs/yolov6/yolov6-face/yolov6_v3_m_syncbn_fast_8xb32-300e_widerface.py
- configs/yolov6/yolov6-face/yolov6_v3_n_syncbn_fast_8xb32-300e_widerface.py
- configs/yolov6/yolov6-face/yolov6_v3_s_syncbn_fast_8xb32-300e_widerface.py
- mmyolo/datasets/__init__.py
- mmyolo/datasets/yolov6_widerface.py
- mmyolo/models/backbones/efficient_rep.py
- mmyolo/models/dense_heads/__init__.py
- mmyolo/models/dense_heads/yolov6_face_head.py
- mmyolo/utils/__init__.py
- mmyolo/utils/face_visualizer.py
- tests/test_models/test_dense_heads/test_yolov6-face_head.py
- tools/model_converters/yolov6-face_v3_to_mmyolo.py
* support the usage of WIDERFace dataset
* add YOLOv6FaceHead
* add YOLOv6 face detection configs
* add a checkpoint convertion script
* add a face visualizer
* fix a bug of YOLOv6CSPBep initialization
Support YOLOv6 face detection
1. add YOLOv6 Face Head and YOLOv6 Face Head Module
2. add YOLOv6-face config
3. add WIDERFace dataset
4. add checkpoint convertion script
5. add a face visualizer
6. fix a bug in YOLOv6CSPBep initialization
Due to the lack of evaluation capability of WIDERFace dataset, I was unable to directly assess whether the reproduced Yolov6-face performance was fully aligned with the original Yolov6-face. So I subjectively compared the output of the two models on the same image and evaluate the performance of repoduced model in WIDERFace using the voc mAP.
- Here are the …
> [FEATURE] Support YOLOv6 v3.0 face detection
