open-mmlab/mmyolo

- docker/Dockerfile
- docs/en/get_started.md
- docs/zh_cn/get_started.md
Dockerfile has room for improvement.
- Decrease docker layer.
- Make docker image smaller. 
Previous built docker image is **`18.1G`**, after my improve, the size of built docker image decrease to `17.9G`. Which means that except the size of the basic image `17.1G`, the size of image layer we built is **20% less**.
> [Feature] Make docker image smaller

- README.md
- README_zh-CN.md
- docs/en/get_started.md
- docs/zh_cn/get_started.md
> [Docs]Change the code about installation

- README.md
- README_zh-CN.md
Modify the installation address in readme. Because there is no special install page in readthedocs, I think the redirect address of install should be get_ started.
> [Doc][Readme]Fix typos in README.md

- README.md
- README_zh-CN.md
- docs/en/advanced_guides/data_flow.md
- docs/en/overview.md
- docs/zh_cn/advanced_guides/data_flow.md
- docs/zh_cn/article.md
- docs/zh_cn/index.rst
- docs/zh_cn/overview.md
- docs/zh_cn/user_guides/yolov5_tutorial.md
Add article and refine tutorial
> Add article and refine tutorial

- .circleci/test.yml
- .pre-commit-config-zh-cn.yaml
- .pre-commit-config.yaml
- setup.cfg
- tests/test_datasets/__init__.py
- tests/test_datasets/test_transforms/__init__.py
- tests/test_engine/__init__.py
- tests/test_engine/test_optimizers/__init__.py
- tests/test_models/__init__.py
- tests/test_models/test_backbone/__init__.py
- tests/test_models/test_data_preprocessor/__init__.py
- tests/test_models/test_dense_heads/__init__.py
- tests/test_models/test_layers/__init__.py
- tests/test_models/test_necks/__init__.py
- tests/test_models/test_task_modules/test_coders/__init__.py
- tests/test_models/test_utils/__init__.py
- tests/test_models/test_utils/test_misc.py
- tests/test_utils/test_setup_env.py
The motivation to upgrade some versions of pre-commit hooks to latest is that `importlib-metadata v5.0.0` which removed deprecated endpoint breaks the flake8. More details at https://stackoverflow.com/questions/73929564/entrypoints-object-has-no-attribute-get-digital-ocean/73932581#73932581.
Refer to https://github.com/open-mmlab/mmengine/pull/576
Upgrade some versions of pre-commit hooks.
> Upgrade pre commit hooks 

- mmyolo/models/necks/base_yolo_neck.py
`heigh` is not an English word. The antonym of `low` is `high`.
Rename `feat_heigh` and `feat_height` to `feat_high`.
> [Fix] correct variable names in base_yolo_neck.py

- docs/en/user_guides/config.md
- docs/zh_cn/user_guides/config.md
- mmyolo/models/backbones/cspnext.py
- mmyolo/models/necks/cspnext_pafpn.py
`YOLOv5CSPDarknet` and `YOLOv6EfficientRep` have the same keys in config files. So need to give a different example.
1. Refine the `__delete__` example in config.md
2. Add missing docstring in cspnext.py
> [Docs] Refine config.md

- docs/en/user_guides/useful_tools.md
- docs/zh_cn/user_guides/useful_tools.md
- tools/misc/extract_subcoco.py
The training dataset of the COCO2017 dataset includes 118k images, and the validation set includes 5k images, which is a relatively large dataset. Loading JSON in debugging or quick verification scenarios will consume more resources and bring slower startup speed.
The `extract_subcoco.py` script provides the ability to extract a specified number of images. The user can use the `-num-img` parameter to get a COCO subset of the specified number of images.
Currently, only support COCO2017. In the future will support user-defined datasets of standard coco JSON format.
The root path folder format is as follows:
```text
├── root
│   ├── annotations
│   ├── train2017
│   ├── val2017
│   ├── test2017
```
1. Extract 10 training images and 10 validation images using only 5k validation sets.
```shell …
```
> [Feature] Add `extract_subcoco` script

- tests/test_models/test_task_modules/test_assigners/test_batch_atss_assigner.py
`test_batch_atss_assigner_with_empty_boxes_and_gt`
> [Fxi] Fix ci bug

- mmyolo/models/backbones/csp_darknet.py
- mmyolo/models/necks/yolox_pafpn.py
Add `use_depthwise` in the yolox backbone and neck to fix training errors of yolox nano.
`csp_darknet.py` and `yolox_pafpn.py`
> [Fix] training errors of yolox nano

- mmyolo/deploy/object_detection.py
rtmdet deploy in mmyolo has failed in mmdeploy's regression test
Add mmdet rewriter for mmyolo because some models in mmyolo multiplex the mmdet rewriters.
None.
Uses in mmdeploy
```bash
python tools/deploy.py ../mmyolo/configs/deploy/detection_tensorrt_dynamic-192x192-960x960.py ../mmyolo/configs/yolov5/yolov5_s-v61_syncbn_8xb16-300e_coco.py https://download.openmmlab.com/mmyolo/v0/yolov5/yolov5_s-v61_syncbn_fast_8xb16-300e_coco/yolov5_s-v61_syncbn_fast_8xb16-300e_coco_20220918_084700-86e02187.pth ../mmyolo/demo/demo.jpg …
```
> [Fix] Fix mmyolo rtmdet deployment.

- demo/image_demo.py
- mmyolo/utils/labelme_utils.py
Add flag for output labelme label file in `image_demo`
demo/image_demo.py
```bash
python demo/image_demo.py \ 
./data/cat \
configs/yolov5/yolov5_s-v61_syncbn_fast_8xb16-300e_coco.py \
work_dirs/yolov5_s-v61_syncbn_fast_8xb16-300e_coco_20220918_084700-86e02187.pth \
--out-dir ./data/cat_label \
--to-labelme
```
- Json file
- labelme UI
> [Feature] Add flag for output labelme label file in `image_demo`

- mmyolo/datasets/transforms/transforms.py
- tests/test_datasets/test_transforms/test_transforms.py
Will crash when 
```python
input_h, input_w = 222, 117
output_h, output_w = (407, 684)
```
Fix scale factor type of LetterResize and YOLOv5KeepRatioResize, from `np` -> `tupe`
```bash
python tools/test.py \
configs/yolov5/yolov5_s-v61_syncbn_fast_8xb16-300e_coco.py 
work_dirs/yolov5_s-v61_syncbn_fast_8xb16-300e_coco_20220918_084700-86e02187.pth 
```
```bash
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.377
Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.571
Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.410
Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.217
Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.425
Average Precision  (AP) @[ IoU=0.50:0.95 | …
```
> [Fix] Fix scale factor type of `LetterResize` and `YOLOv5KeepRatioResize`

- demo/image_demo.py
- mmyolo/utils/labelme_utils.py
- mmyolo/utils/misc.py
- requirements/runtime.txt
- requirements/tests.txt
- tools/analysis_tools/dataset_analysis.py
Add `--class-name` for filter when save to labelme label.
`demo/image_demo.py`
```bash
python demo/image_demo.py \
/data/cat/images \
configs/yolov5/yolov5_s-v61_syncbn_8xb16-300e_coco.py \
work_dirs/yolov5_s-v61_syncbn_fast_8xb16-300e_coco_20220918_084700-86e02187.pth \
--out-dir /data/cat/labels \
--to-labelme \
--class-name cat
```
> [Improvement] Add `--class-name` for filter when save to labelme label.

- tools/dataset_converters/labelme2coco.py
Add output `class_with_id.txt` after labelme2coco
`tools/dataset_converters/labelme2coco.py`
```txt
1 cat
2 dog
3 bicycle
4 motorcycle
```
> [Improvement] Add output `class_with_id.txt` after labelme2coco

- docs/en/deploy/basic_deployment_guide.md
- docs/en/deploy/yolov5_deployment.md
- docs/zh_cn/deploy/basic_deployment_guide.md
- docs/zh_cn/deploy/yolov5_deployment.md
Translate deployment docs
modified:   docs/en/deploy/basic_deployment_guide.md
modified:   docs/en/deploy/yolov5_deployment.md
modified:   docs/zh_cn/deploy/basic_deployment_guide.md
3. If the modification has a potential influence on downstream …
> [Docs] Deployment translation

- docs/zh_cn/algorithm_descriptions/rtmdet_description.md
- mmyolo/datasets/yolov5_coco.py
- mmyolo/deploy/object_detection.py
- mmyolo/engine/hooks/switch_to_deploy_hook.py
- mmyolo/models/backbones/csp_darknet.py
- mmyolo/models/plugins/cbam.py
- mmyolo/models/task_modules/assigners/batch_yolov7_assigner.py
Add docstring and update RTMDet graph
> [Improvement] Add docstring and update RTMDet graph

- tests/test_deploy/test_mmyolo_models.py
- tests/test_deploy/test_object_detection.py
Fix mmyolo ut wrong scope, this bug is exposed after [mmdeploy PR1450](https://github.com/open-mmlab/mmdeploy/pull/1450) merged in mmdeploy.
mmyolo test_deploy folder, change type 'mmdet' to 'mmyolo'
None.
```bash
pytest tests/test_deploy
```
3. If the modification has a potential influence on downstream projects, this PR should be tested …
> [Fix] Fix mmyolo ut scope

- configs/deploy/detection_tensorrt-fp16_dynamic-64x64-1344x1344.py
- tests/regression/mmyolo.yml
support mmyolo regression test
- add regression test yml config: `tests/regression/mmyolo.yml`
- add trt dynamic deploy config: `configs/deploy/detection_tensorrt-fp16_dynamic-64x64-1344x1344.py`
None
1. install mmdeploy
refer to https://mmdeploy.readthedocs.io/en/1.x/get_started.html#get-started
2. soft link files
```bash
ln -sf ${MMYOLO_DIR}/configs/deploy ${MMDEPLOY_DIR}/configs/mmyolo
ln -sf ${MMYOLO_DIR}/tests/regression/mmyolo.yml ${MMDEPLOY_DIR}/tests/regression/mmyolo.yml
```
3. test with mmdeploy
```
cd ${MMDEPLOY_DIR}
python tools/regression_test.py \
--codebase mmyolo \
--backends onnxruntime tensorrt \
--performance \
--work-dir test_mmyolo \
--device cuda
```
2. The modification is covered by complete …
> [Feat]: support mmyolo regression test

- projects/easydeploy/model/__init__.py
- projects/easydeploy/model/backendwrapper.py
- projects/easydeploy/model/model.py
- projects/easydeploy/tools/build_engine.py
- projects/easydeploy/tools/export.py
When we use `--model-only` for running `export.py`, we can export model only onnx without postprocess
> Export onnx for model only

- .circleci/test.yml
- docs/en/algorithm_descriptions/yolov5_description.md
- docs/zh_cn/algorithm_descriptions/yolov5_description.md
- mmyolo/datasets/utils.py
- mmyolo/utils/boxam_utils.py
- tests/test_models/test_detectors/test_yolo_detector.py
- tools/analysis_tools/benchmark.py
Fix CI error due to `np.int` and legacy builder.py, https://github.com/open-mmlab/mmdetection/pull/9479
1. Replace all `np.int` with `np.int64`.
2. Replace all `build_detector` with `MODELS.build`.
3. Using the `main` branch of mmengine instead of the tag version in CI.
> [Fix] Fix CI error due to `np.int` and legacy builder.py

- mmyolo/datasets/transforms/mix_img_transforms.py
- mmyolo/datasets/transforms/transforms.py
- tools/analysis_tools/browse_dataset.py
`np.bool` is a deprecated alias for the builtin bool and it was removed in https://github.com/numpy/numpy/releases/tag/v1.24.0 .
Replace all `np.bool` with `bool`.
> [Fix] Deprecating `np.bool` Type Alias

- mmyolo/datasets/transforms/mix_img_transforms.py
- mmyolo/models/necks/base_yolo_neck.py
Fix docstring graph rendering error of readthedocs.
Add `.. code:: text` before graphs.
> [Fix] Fix docstring graph rendering error of readthedocs

- mmyolo/models/task_modules/assigners/batch_yolov7_assigner.py
when training custom data with yolov7,  it give [RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)]. The same problem was shown [stackoverflow](https://stackoverflow.com/questions/74713315/yolov7-runtimeerror-indices-should-be-either-on-cpu-or-on-the-same-device-as) and [official yolov7 issue#1224](https://github.com/WongKinYiu/yolov7/issues/1224)
The cause seems to be that in `mmyolo/models/task_modules/assigners/batch_yolov7_assigner.py ` line 309 `_from_which_layer = _from_which_layer[fg_mask_inboxes]`, the indices`fg_mask_inboxes` and `_from_which_layer` are not in the same device. 
sys.platform: linux
Python: 3.9.15 (main, Nov 24 2022, 14:31:59) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0,1,2: Tesla T4
CUDA_HOME: …
> Fix the device inconsistency error in yolov7 training

- configs/yolov5/voc/yolov5_s-v61_fast_1xb64-50e_voc.py
- configs/yolov5/yolov5_s-v61_syncbn_fast_1xb4-300e_balloon.py
- demo/image_demo.py
- docs/en/index.rst
- docs/en/notes/compatibility.md
- docs/en/user_guides/yolov5_tutorial.md
- docs/zh_cn/index.rst
- docs/zh_cn/notes/compatibility.md
- docs/zh_cn/user_guides/custom_dataset.md
- docs/zh_cn/user_guides/yolov5_tutorial.md
- mmyolo/utils/boxam_utils.py
- projects/misc/custom_dataset/yolov5_s-v61_syncbn_fast_1xb32-100e_cat.py
- projects/misc/custom_dataset/yolov6_s_syncbn_fast_1xb32-100e_cat.py
- tools/analysis_tools/dataset_analysis.py
Refactor dataset metainfo to lowercase.
1. `DATASET_TYPE` -> `dataset_type`
2. `CLASSES` -> `classes`
3. `PALETTE` -> `palette`
> [Refactor] Refactor dataset metainfo to lowercase

- mmyolo/models/dense_heads/yolov5_head.py
The fake flatten_objectness is incorrect. This results in a wrong zip length.
Fix it with batch size.
1. Pre-commit or other linting tools are used to fix potential lint …
> [Fix] Fix batch inference bug when objectness does not exist.

- mmyolo/models/detectors/yolo_detector.py
> [Fix] Fix typo in `yolo_detector.py`

- configs/yolov7/yolov7_l_syncbn_fast_8x16b-300e_coco.py
- configs/yolov7/yolov7_tiny_syncbn_fast_8x16b-300e_coco.py
- configs/yolov7/yolov7_w-p6_syncbn_fast_8x16b-300e_coco.py
> [Improve] Beautify the YOLOv7 configuration

- projects/easydeploy/deepstream/README.md
- projects/easydeploy/deepstream/README_zh-CN.md
Add documents for newly supported deepstream project.
./projects/easydeploy/deepstream/READEME.md
./projects/easydeploy/deepstream/READEME_zh-CN.md
3. If the modification has a potential influence on downstream projects, this PR should be tested …
> [Docs] DeepStream documentations

- docs/zh_cn/get_started/15_minutes_object_detection.md
- projects/easydeploy/tools/image-demo.py
增加使用 EasyDeploy 完成 ONNX 和 TensorRT 转换部署和基本图片推理的文档
docs/zh_cn/get_started/15_minutes_object_detection.md
projects/easydeploy/tools/image-demo.py
3. If the modification has a potential influence on downstream projects, this PR should be tested with …
> [Docs] add deploy doc to 15_min_od tutorial

- configs/yolov8/README.md
- docs/en/recommended_topics/algorithm_descriptions/yolov8_description.md
- docs/zh_cn/recommended_topics/algorithm_descriptions/yolov8_description.md
Fix typos in the YOLOv8 diagram.
Modify the channels after No.13 `Upsample` from 256 to 512, the channels after No.14 `Concat` from 512 to 768, and the channels after No.17 `Concat` from 512 to 768.
> [Fix] Fix typos in the YOLOv8 diagram

- configs/yolov7/README.md
Fix typos in the YOLOv7 diagram
<div align=center>
New diagram
</div>
> [Docs] Fix typos in the YOLOv7 diagram

- mmyolo/utils/misc.py
When running `demo/demo_large_image.py` on a folder of images, no images were used for inference because the `get_file_list()` function in `mmyolo/utils/misc` does NOT read uppercase extension images when passing a folder as argument.
Example: `Image_001.JPG`, `Image_002.PNG` and `Image_003.TIFF` are NOT returned by the function, but they should. Many cameras output images with uppercase extensions (such as DJI drones, for example). We should not have to rename our images to be able to infer on them.
Simple fix: Inside `get_file_list()`, I simply added the existing flag: `case_sensitive=False` to the `scandir()` function from `mmengine`.
This PR simply allows users to use the `get_file_list()` function on folders that contain uppercase, lowercase, or mixed case image extensions.
> [Bug fix] Fix get_file_list() not returning images with uppercase extension.

- docs/en/useful_tools/log_analysis.md
fix path of analyze_logs.py in en log_analysis.md.
> [Fix] fix path of analyze_logs.py in log_analysis.md

- docs/en/get_started/installation.md
Fix a typo in the documentation.
- Fix a typo in `installation.md`, line 18: `openmom` to `openmim`
4. The documentation has been modified accordingly, like docstring or example tutorials.
> [Docs] Fix typo in English documentation
